### ISSUE TITLE
Get included devices status 

### ISSUE THREAD

**Issue by hayg25** [MaxIV-KitsControls/tango-facadedevice#12]
Dear All, 
is there a way to set as status, the status get from the devices that are linked in the Ds properties. 
Example : 
if I create one Ds with attribute is Att_new = Att1 / Att2 
I would like to show as status ON is Ds_Att1 and Ds_Att2 are ON 
I would like to show as status OFF is Ds_Att1 or Ds_Att2 are OFF 

Thx

**Comment by AntoineDupre** [comment]
Hi @hayg25 

You need to defined to `proxy_attribute` (to connect each state) and then bind them to `state_and_status` :

```python
class Ds(Device):
     ds1_state = proxy_attribute(
        dtype=float,
        property_name='ds1_state_attribute')

    ds2_state = proxy_attribute(
        dtype=float,
        property_name='ds1_state_attribute')

    @state_attribute(
        bind=['ds1_state', 'ds2_state])
    def state_and_status(self, state1, state2):
        if state1 == DevState.ON and state2 == DevState.ON:
            return DevState.ON, "Both device are ON"
        elif  state1 == DevState.ON or state2 == DevState.ON:
            return DevState.ALARM, "One device is not in ON state"
        else:
           return DevState.OFF, "Both device are OFF"
```

**Comment by hayg25** [comment]
Hi @AntoineDupre , 
Thx !
