### ISSUE TITLE
Read Write attribute

### ISSUE THREAD

**Issue by hayg25** [MaxIV-KitsControls/tango-facadedevice#15]
Dear @AntoineDupre, @vxgmichel , 
Is there an example where one could fill an Attribute value (ex motor position) from another Attribute ( Ex Value associated to the motor position, for example a phase, and attenuation etc ), that I need to create. 
The logic should be : 
1 : fill the attenuation value
2: calculate the associated motor position
3: fill the motor position with the calculated value

Thx

**Comment by AntoineDupre** [comment]
Hi hayg25,

Maybe something like that :
```python

class Test(Facade):
    @local_attribute(
        dtype=int,
        access=AttrWriteType.READ_WRITE,)
    def attenuation(self):
        return 1 # Default value

    phase = proxy_attribute(
        dtype=float,
        property_name='PhaseAttribute')

    @logical_attribute(
        dtype=float,
        bind=['attenuation', 'phase'])
    def motor_position(self, attenuation, phase):
        return motor_position * attenuation
    
    @motor_position.notify
    def _on_motor_position(self, pos):
        self.motor_proxy.position = pos.result().value
 
```

**Comment by hayg25** [comment]
Hi @AntoineDupre , 
thanks for your answer. 
How do you define ```motor_proxy``` ? By hard in the code or do you get it also by defining a new alias using the device property ?

**Comment by AntoineDupre** [comment]
Probably through a `device_property`

```python
class Test(Facade):
    motor_name = device_property(dtype=str)
 
    def safe_init_device(self):
        self.motor_proxy = DeviceProxy(self.motor_name)
```


`pos` there is a `facadedevice.graph.RestrictedNode`. 
`motor_position.notify` setup a callback. This callback is set each time the `logical_attribute` is updated.
To get the latest value set to `motor_position` you can get the latest node result. This result is a `triplet` like:
```
triplet(value=196, stamp=1603732129.805444, quality=tango._tango.AttrQuality.ATTR_VALID)
```

**Comment by hayg25** [comment]
I see, 
and in : 
```python
    def motor_position(self, attenuation, phase):
        return motor_position * attenuation
```
what is ```motor_position ``` you use in the return statement ?

**Comment by AntoineDupre** [comment]
hum ... it's a typo 

```python
    def motor_position(self, attenuation, phase):
        return phase * attenuation
```

**Comment by hayg25** [comment]
ok :)
