### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by daneos** [MaxIV-KitsControls/tango-facadedevice#18]
Last version released on PyPI is 1.0.1 which is incompatible with Python 3.10+ (collections API changed), but the latest tag here is 1.0.4 with the collection fix applied.

**Comment by beenje** [comment]
@vxgmichel could you please add me as maintainer to the https://pypi.org/project/facadedevice/ project so we can publish new versions?

My username on pypi is the same as on GitHub: beenje

**Comment by vxgmichel** [comment]
Invite sent :slightly_smiling_face:

**Comment by beenje** [comment]
Thanks @vxgmichel!

We don't use GitHub much. I will move the project to https://gitlab.com/MaxIV and publish the current version.

**Comment by beenje** [comment]
@vxgmichel, sorry I forgot that I also need access to readthedocs: https://app.readthedocs.org/projects/tango-facadedevice/
(same username). Thanks :pray:

**Comment by vxgmichel** [comment]
@beenje no problem I just sent another invite :)

> I will move the project to https://gitlab.com/MaxIV and publish the current version.

Thanks !

**Comment by beenje** [comment]
> @beenje no problem I just sent another invite :)

Thanks again!
