### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by LJBD** [MaxIV-KitsControls/tango-facadedevice#2]
Hello!

Are you planning to release the package on PyPI?
Our interns are working on Dockerising the development environment and I'd like them to install `facadedevice` in an image as well. Therefore, it would be great if there was an option of installing it with a package manager and not from sources.

Best regards,
Łukasz

**Comment by vxgmichel** [comment]
Hi Łukasz,

Alright, I'll do that! In the meantime, you can use:

    pip install git+https://github.com/MaxIV-KitsControls/tango-facadedevice.git

**Comment by vxgmichel** [comment]
Here you go: https://pypi.org/project/facadedevice/
Cheers!

**Comment by LJBD** [comment]
Thanks a lot!
@stanislaw47 - you can now install it using `pip install facadedevice`.
