### ISSUE TITLE
NotImplementedType error with old numpy version

### ISSUE THREAD

**Issue by AntoineDupre** [MaxIV-KitsControls/tango-facadedevice#3]
Hi,

With old  numpy version (under version 1.8.0), the```numpy.core.numeric.array_equal ```method uses ```umath.equal``` method:
```python
return bool(equal(a1,a2).all())
```
This```numpy.core.numeric.array_equal``` is used by```graph.triplet``` to determine if the triplet value has been updated.
This```umath.equal``` method returns a```NotImplementedType``` object if it is called with data structured like the one returned by a```state_attribute``` ((DevState, "Some status"))

This has been changed in numpy 1.8.0 to:
```python
return bool(asarray(a1 == a2).all())
```

You can reproduce this issue running the following test with numpy 1.7.x:
```python
>>> from facadedevice.graph triplet
>>> triplet(["Some status"], 0.0, 1) == triplet(["Some status"], 0.0, 1)
AttributeError: 'NotImplementedType' object has no attribute 'all'
```

The facadedevice requires only PyTango.
PyTango requires numpy >= 1.1
Maybe add a facadevice requirement:  numpy >= 1.8.0 ?

**Comment by vxgmichel** [comment]
> Maybe add a facadevice requirement: numpy >= 1.8.0 ?

Sounds reasonable!

**Comment by LJBD** [comment]
Given that we're using CentOS at Max IV and Solaris which only has numpy 1.7.1 in its official repositories, I'd opt for providing a compatibility layer for older versions of numpy. Would that be OK?

**Comment by AntoineDupre** [comment]
I guess you are right, we should keep this compatibility (see PR #5 )

**Comment by AntoineDupre** [comment]
PR #5  merged.
