### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by cpt-majkel** [MaxIV-KitsControls/tango-facadedevice#4]
Hi @vxgmichel 
Is devicedoc required and compatible when it comes to building documentation for Device Classes with Facade?

**Comment by vxgmichel** [comment]
Hi @cpt-majkel 

I don't think it's compatible, and even if it were you'd be missing important information about specific facade stuff. Moreover I don't really plan to maintain devicedoc anymore, so feel free to pick it up if you want to!
