### ISSUE TITLE
Installed Facade timeout after Init command

### ISSUE THREAD

**Issue by stanislaw55** [MaxIV-KitsControls/tango-facadedevice#7]
Hello,
recently I've been working with `facadedevice` library. I've created sample Facade DS and installed it.  I've used `python setup.py install`. After that, I've tried to use command `Init` but I received error message saying that my test device timed out. Then device stopped responding at all.

When device was started via Astor, whole DS couldn't be killed by Astor. I've had to do it manually with `kill -9`.

To investigate this issue, I've launched  DS directly from my .py file and it was working fine, even `Init`.

**Comment by MikeFalowski** [comment]
It occurred, that there was an error in device code:

```
run = BooleanopFacade.run_server()

if __name__ == '__main__':
    run()
```
In this example server is being started during `import`, which causes later problems.

Changing to:

```
run = BooleanopFacade.run_server

if __name__ == '__main__':
    run()
```
 solved the problem.

I think that issue can be closed.

**Comment by vxgmichel** [comment]
Ok thanks!
