### ISSUE TITLE
Spectrum attributes

### ISSUE THREAD

**Issue by stanislaw55** [MaxIV-KitsControls/tango-facadedevice#8]
Hello!

Here's my case:
I've got one device server with many spectrum attributes. For me it would be useful if I could create `proxy_attribute` or `logical_attribute` just for one element of my device server `spectrum_attribute`. 
Quick example:

Source device server
```python
from tango.server import Device, attribute

class MyDS(Device):
    @attribute(dtype=(float,),
                       max_dim_x=8)
    def MySpectrumAttr(self):
        return self.my_spectrum_attr
```

Facade device server
```python
from facadedevice import Facade, proxy_attribute

class MyFacade(Facade):
    @proxy_attribute(dtype=float,  # or logical_attribute, if necessary
                                 property_name="MySpectrumAttrAttribute")
    def MyScalarAttr(self):
        return self.my_scalar_attr
```

I've tried during configuration with Jive, just provide `my/ds/instance/my_spectrum_attr[index]` but it complained about not finding attribute called `my_spectrum_att[index]`

Is it possible in any way?

**Comment by vxgmichel** [comment]
Hi @stanislaw55,

Tango doesn't support indexing on spectrum and image attributes. 

However, you can still use a logical attribute to index the spectrum locally:

```python
class MyFacade(Facade):

    index = device_property(dtype=int, default_value=0)

    MySpectrum = proxy_attribute(property_name='MySpectrumAttrAttribute')

    @logical_attribute(bind=['MySpectrum'])
    def MyScalar(spectrum):
        return spectrum[self.index]
```

**Comment by stanislaw55** [comment]
Hi @vxgmichel 
First of all, thank you for rapid response!
I've been thinking about something similar as a solution, but wasn't sure it's the right aproach. Thank you for resolving my doubts!
