### ISSUE TITLE
Problem with setting proxy attribute through command and graph

### ISSUE THREAD

**Issue by MikeFalowski** [MaxIV-KitsControls/tango-facadedevice#9]
Hi!
I tried to set 2 proxy attributes through command like this:
```python
value1 =  proxy_attribute(
    dtype='bool',
    access=AttrWriteType.READ, 
    property_name='valueAttr')

value2 =  proxy_attribute(
    dtype='bool',
    access=AttrWriteType.READ_WRITE, 
    property_name='valueAttr')

    @command
    def SetTrue(self):
        node1 = self.graph['value1']
        node2 = self.graph['value2']
        node1.set_result(triplet(True))
        node2.set_result(triplet(True))
```

Unfortunately, values change only in the facade and not in the original device (I used AtkPanel to debug) but if I change value in the AtkPanel of the facade, it's changes in both devices (of course if it's writeable).

Any idea what could be wrong with the code or how to solve that problem?

Cheers,
Mike

**Comment by vxgmichel** [comment]
Hi Mike,

The reactive graph is used for propagating changes from the underlying devices (in the case of `proxy_attribute`), so it's only related to the reading mechanism.

In order to perform a write operation on the original device, the simplest approach is to use a proxy:

```python
@command
def set_true(self):
    proxy  = DeviceProxy(self.get_name())
    proxy.write_attribute('value2', True)
```

An internal call to `_run_
```python
@command
def set_true(self):
    self._run_proxy_command('value2', True)
```
Hope that helps.

**Comment by MikeFalowski** [comment]
Thanks Vincent!
That seems to be more simpler solution.
Kind regards,
Mike
PS: I'm closing the issue.
